### ISSUE TITLE
Asset support for a custom wp-content directory?

### ISSUE THREAD

**Issue by matgargano** [humanmade/react-wp-scripts#33]
I am likely missing something but I am encountering an issue with asset location references when **sharing** a plugin created with this project.  

If one of my WordPress instances is using [Bedrock](https://roots.io/bedrock/)'s directory structure, where it uses `/app` instead of `/wp-content` and I set the `package.json` `homepage` value to `https://example.com/app/plugins/barfoo/build` it works (as expected); however, if I share the plugin with someone who is using the typical `/wp-content` directory structure it doesn't (the assets point to `/app` as expected)

Is there any way to mitigate this? I.e. filter the `homepage` setting or some other way that I can't think of?

**Comment by rmccue** [comment]
This is likely due to your [`homepage` setting](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#building-for-relative-paths), as there's nothing in react-wp-scripts itself around this.

Alas, `homepage` is used during the build step, so this URL is compiled into your app. You can try using relative URLs for this, or you may need some other webpack-level configuration; seems like [you can override Webpack's config at runtime?](https://webpack.js.org/guides/public-path/#on-the-fly).

If there's some solution we can include in react-wp-scripts to help with this, would love to know.

**Comment by matgargano** [comment]
OK thanks. This is definitely due to the homepage setting. I'm going to try a few things and see if this can be resolved.

I'd consider this somewhat of a blocker before this can be used as a tried and true way to integrate react into projects. 

It's perfect otherwise, thanks for it!

**Comment by matgargano** [comment]
OK so here's what I got...

This isn't a fix for sharing -- but we develop locally using `/app` and the client uses `/wp-content` so we are going to go with

```
{
  "name": "foo-project",
  "version": "0.1.0",
  "private": true,
  "homepage": "http://intlsafadsfst.coms/wp-content/plugins/barfoo/build",
  "dependencies": {
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-wp-scripts": "0.2.0"
  },
  "scripts": {
    "start": "react-wp-scripts start",
    "build": "react-scripts build",
    "build:dev": "export PUBLIC_URL=\"/app/plugins/barfoo/build\" && react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

```


still not distributable, but it's working...

**Comment by rmccue** [comment]
This was fixed in the updates to CRA v2+.
